import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import './globals.css';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Eduardo | Full Stack Developer',
    description: 'Generated by create next app',
    keywords: [
        'Full Stack Developer',
        'React Developer',
        'Node.js Developer',
        'Portfolio',
        'Projects',
        'Skills',
    ],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={poppins.className} suppressHydrationWarning>
                {children}
            </body>
        </html>
    );
}
